In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [15]:
X1 = np.array([-0.5, -0.5, -0.5, -0.5])

np.dot(X1.reshape(-1, 1), X1.reshape(1, -1))

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

In [11]:
X1 = np.array([-0.333, -0.333, -0.333, -0.333])

np.dot(X1.reshape(-1, 1), X1.reshape(1, -1))

array([[0.110889, 0.110889, 0.110889, 0.110889],
       [0.110889, 0.110889, 0.110889, 0.110889],
       [0.110889, 0.110889, 0.110889, 0.110889],
       [0.110889, 0.110889, 0.110889, 0.110889]])

In [12]:
X1 = np.array([1.667, 1.667, 1.667, 1.667])

np.dot(X1.reshape(-1, 1), X1.reshape(1, -1))

array([[2.778889, 2.778889, 2.778889, 2.778889],
       [2.778889, 2.778889, 2.778889, 2.778889],
       [2.778889, 2.778889, 2.778889, 2.778889],
       [2.778889, 2.778889, 2.778889, 2.778889]])

In [13]:
import numpy as np

# Define the dataset
X1 = np.array([[2, 3, 4, 5],
               [3, 4, 5, 6],
               [5, 6, 7, 8]])

X2 = np.array([[2, 1, 3, 4],
               [3, 2, 4, 5]])

# Compute the class means
m1 = np.mean(X1, axis=0)
m2 = np.mean(X2, axis=0)

# Print the class means
print("Class 1 mean:", m1)
print("Class 2 mean:", m2)


Class 1 mean: [3.33333333 4.33333333 5.33333333 6.33333333]
Class 2 mean: [2.5 1.5 3.5 4.5]


In [14]:
# Compute the within-class scatter matrix for Class 1
S_w1 = np.dot((X1 - m1).T, (X1 - m1))

# Compute the within-class scatter matrix for Class 2
S_w2 = np.dot((X2 - m2).T, (X2 - m2))

# Total within-class scatter matrix
S_w = S_w1 + S_w2

# Print the within-class scatter matrices
print("Within-class scatter matrix for Class 1:")
print(S_w1)
print("\nWithin-class scatter matrix for Class 2:")
print(S_w2)
print("\nTotal within-class scatter matrix:")
print(S_w)


Within-class scatter matrix for Class 1:
[[4.66666667 4.66666667 4.66666667 4.66666667]
 [4.66666667 4.66666667 4.66666667 4.66666667]
 [4.66666667 4.66666667 4.66666667 4.66666667]
 [4.66666667 4.66666667 4.66666667 4.66666667]]

Within-class scatter matrix for Class 2:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

Total within-class scatter matrix:
[[5.16666667 5.16666667 5.16666667 5.16666667]
 [5.16666667 5.16666667 5.16666667 5.16666667]
 [5.16666667 5.16666667 5.16666667 5.16666667]
 [5.16666667 5.16666667 5.16666667 5.16666667]]
