In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [41]:
X1 = np.array([2.1, 1.3, 1, -1.9])

np.dot(X1.reshape(-1, 1), X1.reshape(1, -1))

array([[ 4.41,  2.73,  2.1 , -3.99],
       [ 2.73,  1.69,  1.3 , -2.47],
       [ 2.1 ,  1.3 ,  1.  , -1.9 ],
       [-3.99, -2.47, -1.9 ,  3.61]])

In [22]:
X1 = np.array([-0.5, -1.7, -1.1, -1.1])

3 * np.dot(X1.reshape(-1, 1), X1.reshape(1, -1))

array([[0.75, 2.55, 1.65, 1.65],
       [2.55, 8.67, 5.61, 5.61],
       [1.65, 5.61, 3.63, 3.63],
       [1.65, 5.61, 3.63, 3.63]])

In [12]:
X1 = np.array([1.667, 1.667, 1.667, 1.667])

np.dot(X1.reshape(-1, 1), X1.reshape(1, -1))

array([[2.778889, 2.778889, 2.778889, 2.778889],
       [2.778889, 2.778889, 2.778889, 2.778889],
       [2.778889, 2.778889, 2.778889, 2.778889],
       [2.778889, 2.778889, 2.778889, 2.778889]])

In [45]:
import numpy as np

# Sample data
X = np.array([[3, 6, 4, 10],
              [2, 7, 5, 9],
              [1, 6, 7, 4],
              [4, 9, 8, 3],
              [7, 8, 6, 6]])

y = np.array([0, 0, 0, 1, 1])  # Class labels

# Separate data by class
X_class1 = X[y == 0]
X_class2 = X[y == 1]

# Compute class means
mean_class1 = np.mean(X_class1, axis=0)
mean_class2 = np.mean(X_class2, axis=0)

# Compute within-class scatter matrix Sw
n_features = X.shape[1]
Sw = np.zeros((n_features, n_features))
for xi in X_class1:
    diff = xi - mean_class1
    Sw += np.outer(diff, diff)
for xi in X_class2:
    diff = xi - mean_class2
    Sw += np.outer(diff, diff)

# Compute between-class scatter matrix Sb
diff_means = mean_class1 - mean_class2
Sb = np.outer(diff_means, diff_means)

# Compute eigenvalues and eigenvectors of Sw^-1 * Sb
eigenvalues, eigenvectors = np.linalg.eig(np.linalg.inv(Sw).dot(Sb))

# Sort eigenvalues and corresponding eigenvectors
idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
eigenvectors = eigenvectors[:, idx]

# Choose the top k eigenvectors (k=1 for 1D projection)
k = 1
projection_matrix = eigenvectors[:, :k]

# Project the data onto the new subspace
X_lda = X.dot(projection_matrix)

print("Original data shape:", X.shape)
print("Transformed data shape:", X_lda.shape)
print("Transformed data:")
print(X_lda)


Original data shape: (5, 4)
Transformed data shape: (5, 1)
Transformed data:
[[-6.7753605 ]
 [-6.83708072]
 [-3.41375479]
 [-5.14599117]
 [-6.20480617]]


In [47]:
np.linalg.inv(Sw).dot(Sb)

array([[ 7.12430556e+01,  4.41028439e+01,  3.39252646e+01,
        -6.44580026e+01],
       [-1.57625987e+16, -9.75779919e+15, -7.50599938e+15,
         1.42613988e+16],
       [ 3.15251974e+16,  1.95155984e+16,  1.50119988e+16,
        -2.85227976e+16],
       [ 1.57625987e+16,  9.75779919e+15,  7.50599938e+15,
        -1.42613988e+16]])

In [13]:
import numpy as np

# Define the dataset
X1 = np.array([[2, 3, 4, 5],
               [3, 4, 5, 6],
               [5, 6, 7, 8]])

X2 = np.array([[2, 1, 3, 4],
               [3, 2, 4, 5]])

# Compute the class means
m1 = np.mean(X1, axis=0)
m2 = np.mean(X2, axis=0)

# Print the class means
print("Class 1 mean:", m1)
print("Class 2 mean:", m2)


Class 1 mean: [3.33333333 4.33333333 5.33333333 6.33333333]
Class 2 mean: [2.5 1.5 3.5 4.5]


In [14]:
# Compute the within-class scatter matrix for Class 1
S_w1 = np.dot((X1 - m1).T, (X1 - m1))

# Compute the within-class scatter matrix for Class 2
S_w2 = np.dot((X2 - m2).T, (X2 - m2))

# Total within-class scatter matrix
S_w = S_w1 + S_w2

# Print the within-class scatter matrices
print("Within-class scatter matrix for Class 1:")
print(S_w1)
print("\nWithin-class scatter matrix for Class 2:")
print(S_w2)
print("\nTotal within-class scatter matrix:")
print(S_w)


Within-class scatter matrix for Class 1:
[[4.66666667 4.66666667 4.66666667 4.66666667]
 [4.66666667 4.66666667 4.66666667 4.66666667]
 [4.66666667 4.66666667 4.66666667 4.66666667]
 [4.66666667 4.66666667 4.66666667 4.66666667]]

Within-class scatter matrix for Class 2:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

Total within-class scatter matrix:
[[5.16666667 5.16666667 5.16666667 5.16666667]
 [5.16666667 5.16666667 5.16666667 5.16666667]
 [5.16666667 5.16666667 5.16666667 5.16666667]
 [5.16666667 5.16666667 5.16666667 5.16666667]]


In [48]:
import numpy as np

# Define matrices A and B
A = np.array([[6.5, -1.5, -6, 10.5],
                    [-1.5, 1.1667, 0.6667, -0.1667],
                    [-6, 0.6667, 6.6667, -12.6667],
                    [10.5, -0.1667, -12.6667, 25.1667]])

B = np.array([[10.29, 6.37014, 4.9002, -9.31014],
                    [6.3702, 3.94351, 3.0334, -5.76354667],
                    [4.9002, 3.03349, 2.3335, -4.43353],
                    [-9.3102, -5.76355, -4.43353, 8.42358667]])

# Compute the inverse of matrix A
A_inv = np.linalg.inv(A)

# Calculate the dot product of the inverse of A and matrix B
dot_product = np.dot(A_inv, B)

# Display the result
print("Dot Product of Inverse of A and B:")
print(dot_product)
eigenvalues, eigenvectors = np.linalg.eig(dot_product)

Dot Product of Inverse of A and B:
[[ 4.84314539e+01  2.99818746e+01  2.30633550e+01 -4.38193516e+01]
 [-1.89151184e+15 -1.17096164e+15 -9.00697407e+14  1.71139145e+15]
 [ 3.78302369e+15  2.34192328e+15  1.80139481e+15 -3.42278290e+15]
 [ 1.89151184e+15  1.17096164e+15  9.00697407e+14 -1.71139145e+15]]


In [49]:
eigenvalues

array([-1.25000000e-01+0.j        , -1.08095827e+15+0.j        ,
       -5.63131588e-03+0.82831544j, -5.63131588e-03-0.82831544j])

In [50]:
eigenvectors

array([[ 2.27203544e-01+0.j        ,  1.04519057e-14+0.j        ,
        -2.13139746e-04+0.00147903j, -2.13139746e-04-0.00147903j],
       [-3.97571492e-01+0.j        , -4.08248290e-01+0.j        ,
         9.61934858e-02-0.22991297j,  9.61934858e-02+0.22991297j],
       [ 7.95142985e-01+0.j        ,  8.16496581e-01+0.j        ,
        -8.71324625e-01+0.j        , -8.71324625e-01-0.j        ],
       [ 3.97571492e-01+0.j        ,  4.08248290e-01+0.j        ,
        -3.92992559e-01-0.15567547j, -3.92992559e-01+0.15567547j]])